import Link from "next/link";
import { auth, signOut } from "@/lib/auth";
import { redirect } from "next/navigation";

const nav = [["⌂", "Beranda", "/dashboard"], ["↔", "Transaksi", "/transaksi"], ["＋", "Catat", "/catat/pengeluaran"], ["◎", "Target", "/target"], ["▥", "Laporan", "/laporan"]];
export async function AppShell({ children, current = "" }: { children: React.ReactNode; current?: string }) {
  const session = await auth(); if (!session?.user) redirect("/masuk");
  const name = session.user.name || "Pengguna";
  return <div className="app"><aside className="sidebar"><Link className="logo" href="/dashboard"><span className="logo-mark">k</span>kantong</Link><div className="nav-label">MENU</div><nav className="nav-list">{nav.map(([icon,label,href])=><Link className={`nav-link ${current===label?"active":""}`} href={href} key={label}><span className="nav-icon">{icon}</span>{label}</Link>)}<Link className={`nav-link ${current==="Dompet"?"active":""}`} href="/dompet"><span className="nav-icon">▣</span>Dompet</Link><Link className={`nav-link ${current==="Notifikasi"?"active":""}`} href="/notifikasi"><span className="nav-icon">♧</span>Notifikasi</Link></nav><div className="side-bottom"><Link className="nav-link" href="/profil"><span className="nav-icon">⚙</span>Profil</Link><div className="profile-mini"><span className="avatar">{name.slice(0,1).toUpperCase()}</span><div><strong>{name}</strong><small>Akun pribadi</small></div></div></div></aside><main className="main"><header className="topbar"><div className="greeting"><h1>{current==="Beranda"?`Halo, ${name.split(" ")[0]} 👋`:current}</h1><div className="muted">{current==="Beranda"?"Yuk, cek kabar keuanganmu hari ini.":"Atur keuanganmu dengan lebih tenang."}</div></div><div className="top-actions"><Link className="icon-btn" aria-label="Notifikasi" href="/notifikasi">♧<span className="badge-dot"/></Link><Link className="btn" href="/catat/pengeluaran">＋ Catat transaksi</Link><form action={async()=>{ "use server"; await signOut({redirectTo:"/masuk"}); }}><button className="icon-btn" aria-label="Keluar" title="Keluar">↗</button></form></div></header>{children}</main><nav className="mobile-nav">{nav.map(([icon,label,href])=><Link className={current===label?"active":""} href={href} key={label}><span className="nav-icon">{icon}</span><span>{label}</span></Link>)}</nav></div>;
}
